### ISSUE TITLE
No dropdown

### ISSUE THREAD

**Issue by punzweb** [bratiask/silverstripe-autotranslate#1]
Hi there, 

I've followed the instructions in readme.md and the dropdown did not appear on the translatable fields in CMS as per screenshots.
![image](https://user-images.githubusercontent.com/70352339/103844731-61a4b980-50ff-11eb-984b-fb926ade8dea.png)

Fluent version 5 -> downgraded to 4.3 due to the req.
Silverstripe version 4.6

Could you please help advise if there is an update or if I've missed any steps?

Kind regards,
Priscilla

**Comment by siGurd87** [comment]
Hi there,
You should add AutotranslateExtension to object(s) that should have autotranslate option eg.Page. Yaml config example.

``` yaml
---
Name: page-autotranslate
After: '#versionedfiles'
---
Page:
  extensions:
    - Bratiask\Autotranslate\Extension\AutotranslateExtension
```

Kind regards,
siGurd
